/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package simplecalculator;

import java.io.BufferedOutputStream;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.OutputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import static java.nio.file.StandardOpenOption.CREATE;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author rcc
 */
public class CalculatorFrame extends javax.swing.JFrame {
    
    private double total1 = 0.0;
    private double total2 = 0.0;
    private char math_operator;
    private String memoryStore;
    private String zero = "0";
    
        
    /**
     * Creates new form CalculatorFrame
     */
    
    
    public CalculatorFrame() {
        initComponents();
    }

    // utility method to handle updating the InputOutputTextField when a new
    // character is entered.
    private void InputOutputTextFieldUpdate(Character c)
    {
        InputOutputTextField.setText(InputOutputTextField.getText()+c);
        this.ButtonClear.setEnabled(true);
        this.ButtonClear.setText("CE");
    }
    
    private void getOperator (String btnText){
        math_operator = btnText.charAt(0);
        total1 = total1 + Double.parseDouble( InputOutputTextField.getText( ) ) ;
        InputOutputTextField.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        textModeFrame = new javax.swing.JFrame();
        textModeInput = new javax.swing.JTextField();
        buttonA = new javax.swing.JButton();
        buttonB = new javax.swing.JButton();
        buttonC = new javax.swing.JButton();
        buttonD = new javax.swing.JButton();
        buttonE = new javax.swing.JButton();
        buttonF = new javax.swing.JButton();
        buttonG = new javax.swing.JButton();
        buttonH = new javax.swing.JButton();
        buttonI = new javax.swing.JButton();
        buttonJ = new javax.swing.JButton();
        buttonK = new javax.swing.JButton();
        buttonL = new javax.swing.JButton();
        buttonM = new javax.swing.JButton();
        buttonN = new javax.swing.JButton();
        buttonO = new javax.swing.JButton();
        buttonP = new javax.swing.JButton();
        buttonQ = new javax.swing.JButton();
        buttonR = new javax.swing.JButton();
        buttonS = new javax.swing.JButton();
        buttonT = new javax.swing.JButton();
        buttonU = new javax.swing.JButton();
        buttonV = new javax.swing.JButton();
        buttonW = new javax.swing.JButton();
        buttonX = new javax.swing.JButton();
        buttonY = new javax.swing.JButton();
        buttonZ = new javax.swing.JButton();
        buttonSpace = new javax.swing.JButton();
        buttonTextClear = new javax.swing.JButton();
        buttonShift = new javax.swing.JToggleButton();
        convertBinary = new javax.swing.JButton();
        binaryExport = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        menuClose = new javax.swing.JMenuItem();
        menuHelp = new javax.swing.JMenu();
        binaryWindow = new javax.swing.JDialog();
        binaryTextArea = new java.awt.TextArea();
        InputOutputTextField = new javax.swing.JTextField();
        Button7 = new javax.swing.JButton();
        Button8 = new javax.swing.JButton();
        Button9 = new javax.swing.JButton();
        ButtonDivide = new javax.swing.JButton();
        ButtonMemoryStore = new javax.swing.JButton();
        Button4 = new javax.swing.JButton();
        Button5 = new javax.swing.JButton();
        Button6 = new javax.swing.JButton();
        ButtonMultiply = new javax.swing.JButton();
        ButtonMemoryClear = new javax.swing.JButton();
        Button1 = new javax.swing.JButton();
        Button2 = new javax.swing.JButton();
        Button3 = new javax.swing.JButton();
        ButtonAddition = new javax.swing.JButton();
        ButtonMemoryRecall = new javax.swing.JButton();
        ButtonClear = new javax.swing.JButton();
        Button0 = new javax.swing.JButton();
        ButtonDecimal = new javax.swing.JButton();
        ButtonSubtraction = new javax.swing.JButton();
        ButtonEquals = new javax.swing.JButton();
        ButtonSquare = new javax.swing.JButton();
        CalculatorMenuBar = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        changeMode = new javax.swing.JMenuItem();
        HelpMenu = new javax.swing.JMenu();

        textModeFrame.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        textModeFrame.setLocation(new java.awt.Point(700, 300));
        textModeFrame.setMaximizedBounds(new java.awt.Rectangle(0, 0, 500, 500));
        textModeFrame.setPreferredSize(new java.awt.Dimension(500, 350));
        textModeFrame.setResizable(false);
        textModeFrame.setSize(new java.awt.Dimension(480, 280));

        buttonA.setText("A");
        buttonA.setPreferredSize(new java.awt.Dimension(50, 50));
        buttonA.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buttonAActionPerformed(evt);
            }
        });

        buttonB.setText("B");
        buttonB.setPreferredSize(new java.awt.Dimension(50, 50));
        buttonB.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buttonBActionPerformed(evt);
            }
        });

        buttonC.setText("C");
        buttonC.setPreferredSize(new java.awt.Dimension(50, 50));
        buttonC.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buttonCActionPerformed(evt);
            }
        });

        buttonD.setText("D");
        buttonD.setPreferredSize(new java.awt.Dimension(50, 50));
        buttonD.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buttonDActionPerformed(evt);
            }
        });

        buttonE.setText("E");
        buttonE.setPreferredSize(new java.awt.Dimension(50, 50));
        buttonE.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buttonEActionPerformed(evt);
            }
        });

        buttonF.setText("F");
        buttonF.setPreferredSize(new java.awt.Dimension(50, 50));
        buttonF.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buttonFActionPerformed(evt);
            }
        });

        buttonG.setText("G");
        buttonG.setPreferredSize(new java.awt.Dimension(50, 50));
        buttonG.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buttonGActionPerformed(evt);
            }
        });

        buttonH.setText("H");
        buttonH.setPreferredSize(new java.awt.Dimension(50, 50));
        buttonH.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buttonHActionPerformed(evt);
            }
        });

        buttonI.setText("I");
        buttonI.setPreferredSize(new java.awt.Dimension(50, 50));
        buttonI.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buttonIActionPerformed(evt);
            }
        });

        buttonJ.setText("J");
        buttonJ.setPreferredSize(new java.awt.Dimension(50, 50));
        buttonJ.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buttonJActionPerformed(evt);
            }
        });

        buttonK.setText("K");
        buttonK.setPreferredSize(new java.awt.Dimension(50, 50));
        buttonK.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buttonKActionPerformed(evt);
            }
        });

        buttonL.setText("L");
        buttonL.setPreferredSize(new java.awt.Dimension(50, 50));
        buttonL.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buttonLActionPerformed(evt);
            }
        });

        buttonM.setText("M");
        buttonM.setPreferredSize(new java.awt.Dimension(50, 50));
        buttonM.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buttonMActionPerformed(evt);
            }
        });

        buttonN.setText("N");
        buttonN.setPreferredSize(new java.awt.Dimension(50, 50));
        buttonN.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buttonNActionPerformed(evt);
            }
        });

        buttonO.setText("O");
        buttonO.setPreferredSize(new java.awt.Dimension(50, 50));
        buttonO.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buttonOActionPerformed(evt);
            }
        });

        buttonP.setText("P");
        buttonP.setPreferredSize(new java.awt.Dimension(50, 50));
        buttonP.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buttonPActionPerformed(evt);
            }
        });

        buttonQ.setText("Q");
        buttonQ.setPreferredSize(new java.awt.Dimension(50, 50));
        buttonQ.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buttonQActionPerformed(evt);
            }
        });

        buttonR.setText("R");
        buttonR.setPreferredSize(new java.awt.Dimension(50, 50));
        buttonR.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buttonRActionPerformed(evt);
            }
        });

        buttonS.setText("S");
        buttonS.setPreferredSize(new java.awt.Dimension(50, 50));
        buttonS.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buttonSActionPerformed(evt);
            }
        });

        buttonT.setText("T");
        buttonT.setPreferredSize(new java.awt.Dimension(50, 50));
        buttonT.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buttonTActionPerformed(evt);
            }
        });

        buttonU.setText("U");
        buttonU.setPreferredSize(new java.awt.Dimension(50, 50));
        buttonU.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buttonUActionPerformed(evt);
            }
        });

        buttonV.setText("V");
        buttonV.setPreferredSize(new java.awt.Dimension(50, 50));
        buttonV.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buttonVActionPerformed(evt);
            }
        });

        buttonW.setText("W");
        buttonW.setPreferredSize(new java.awt.Dimension(50, 50));
        buttonW.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buttonWActionPerformed(evt);
            }
        });

        buttonX.setText("X");
        buttonX.setPreferredSize(new java.awt.Dimension(50, 50));
        buttonX.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buttonXActionPerformed(evt);
            }
        });

        buttonY.setText("Y");
        buttonY.setPreferredSize(new java.awt.Dimension(50, 50));
        buttonY.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buttonYActionPerformed(evt);
            }
        });

        buttonZ.setText("Z");
        buttonZ.setPreferredSize(new java.awt.Dimension(50, 50));
        buttonZ.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buttonZActionPerformed(evt);
            }
        });

        buttonSpace.setText("Space");
        buttonSpace.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buttonSpaceActionPerformed(evt);
            }
        });

        buttonTextClear.setText("Clear");
        buttonTextClear.setPreferredSize(new java.awt.Dimension(50, 50));
        buttonTextClear.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buttonTextClearActionPerformed(evt);
            }
        });

        buttonShift.setText("Shift");
        buttonShift.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                buttonShiftMouseClicked(evt);
            }
        });

        convertBinary.setText("Binary Conversion");
        convertBinary.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                convertBinaryActionPerformed(evt);
            }
        });

        binaryExport.setText("Export Binary to file");
        binaryExport.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                binaryExportActionPerformed(evt);
            }
        });

        menuFile.setText("File");

        menuClose.setText("Close");
        menuClose.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                menuCloseActionPerformed(evt);
            }
        });
        menuFile.add(menuClose);

        jMenuBar1.add(menuFile);

        menuHelp.setText("Help");
        jMenuBar1.add(menuHelp);

        textModeFrame.setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout textModeFrameLayout = new javax.swing.GroupLayout(textModeFrame.getContentPane());
        textModeFrame.getContentPane().setLayout(textModeFrameLayout);
        textModeFrameLayout.setHorizontalGroup(
            textModeFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(textModeFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(textModeFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(textModeFrameLayout.createSequentialGroup()
                        .addComponent(buttonI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonO, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonP, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(textModeFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(textModeInput, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(textModeFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(textModeFrameLayout.createSequentialGroup()
                                .addGroup(textModeFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(textModeFrameLayout.createSequentialGroup()
                                        .addComponent(buttonQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(buttonR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(buttonS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(buttonT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(buttonU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(buttonV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(textModeFrameLayout.createSequentialGroup()
                                        .addComponent(buttonY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(textModeFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(convertBinary)
                                            .addGroup(textModeFrameLayout.createSequentialGroup()
                                                .addComponent(buttonZ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(buttonSpace, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(textModeFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(buttonW, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buttonShift))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(textModeFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(buttonX, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                                    .addComponent(buttonTextClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(textModeFrameLayout.createSequentialGroup()
                                .addComponent(buttonA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonG, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonH, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(textModeFrameLayout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addComponent(binaryExport, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        textModeFrameLayout.setVerticalGroup(
            textModeFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(textModeFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textModeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(textModeFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonA, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonB, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonC, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonD, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonE, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonG, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonH, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(textModeFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonI, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonJ, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonK, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonL, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonM, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonN, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonO, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonP, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(textModeFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(textModeFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buttonQ, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(buttonR, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(buttonS, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(buttonT, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(buttonU, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(buttonV, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(buttonW, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(buttonX, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(textModeFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonY, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonZ, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSpace, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonTextClear, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonShift, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(textModeFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(convertBinary)
                    .addComponent(binaryExport))
                .addContainerGap())
        );

        binaryWindow.setLocation(new java.awt.Point(700, 300));
        binaryWindow.setMinimumSize(new java.awt.Dimension(500, 500));

        binaryTextArea.setEditable(false);

        javax.swing.GroupLayout binaryWindowLayout = new javax.swing.GroupLayout(binaryWindow.getContentPane());
        binaryWindow.getContentPane().setLayout(binaryWindowLayout);
        binaryWindowLayout.setHorizontalGroup(
            binaryWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(binaryWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(binaryTextArea, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE))
        );
        binaryWindowLayout.setVerticalGroup(
            binaryWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(binaryWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(binaryTextArea, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setName(""); // NOI18N
        setResizable(false);

        InputOutputTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        InputOutputTextField.setText("0");
        InputOutputTextField.setToolTipText("Input numeric value");
        InputOutputTextField.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                InputOutputTextFieldActionPerformed(evt);
            }
        });

        Button7.setLabel("7");
        Button7.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                Button7ActionPerformed(evt);
            }
        });

        Button8.setText("8");
        Button8.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                Button8ActionPerformed(evt);
            }
        });

        Button9.setText("9");
        Button9.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                Button9ActionPerformed(evt);
            }
        });

        ButtonDivide.setText("/");
        ButtonDivide.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ButtonDivideActionPerformed(evt);
            }
        });

        ButtonMemoryStore.setText("Ms");
        ButtonMemoryStore.setToolTipText("Memory Store");
        ButtonMemoryStore.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ButtonMemoryStoreActionPerformed(evt);
            }
        });

        Button4.setText("4");
        Button4.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                Button4ActionPerformed(evt);
            }
        });

        Button5.setText("5");
        Button5.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                Button5ActionPerformed(evt);
            }
        });

        Button6.setText("6");
        Button6.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                Button6ActionPerformed(evt);
            }
        });

        ButtonMultiply.setText("*");
        ButtonMultiply.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ButtonMultiplyActionPerformed(evt);
            }
        });

        ButtonMemoryClear.setText("Mc");
        ButtonMemoryClear.setToolTipText("Memory Clear");
        ButtonMemoryClear.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ButtonMemoryClearActionPerformed(evt);
            }
        });

        Button1.setText("1");
        Button1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                Button1ActionPerformed(evt);
            }
        });

        Button2.setText("2");
        Button2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                Button2ActionPerformed(evt);
            }
        });

        Button3.setText("3");
        Button3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                Button3ActionPerformed(evt);
            }
        });

        ButtonAddition.setText("+");
        ButtonAddition.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ButtonAdditionActionPerformed(evt);
            }
        });

        ButtonMemoryRecall.setText("M");
        ButtonMemoryRecall.setToolTipText("Get Value From Memory");
        ButtonMemoryRecall.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ButtonMemoryRecallActionPerformed(evt);
            }
        });

        ButtonClear.setText("C");
        ButtonClear.setEnabled(true);
        ButtonClear.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ButtonClearActionPerformed(evt);
            }
        });

        Button0.setText("0");
        Button0.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                Button0ActionPerformed(evt);
            }
        });

        ButtonDecimal.setText(".");
        ButtonDecimal.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ButtonDecimalActionPerformed(evt);
            }
        });

        ButtonSubtraction.setText("-");
        ButtonSubtraction.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ButtonSubtractionActionPerformed(evt);
            }
        });

        ButtonEquals.setText("=");
        ButtonEquals.setToolTipText("");
        ButtonEquals.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ButtonEqualsActionPerformed(evt);
            }
        });

        ButtonSquare.setText("x^2");
        ButtonSquare.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ButtonSquareActionPerformed(evt);
            }
        });

        FileMenu.setText("File");

        changeMode.setText("Text Mode");
        changeMode.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                changeModeActionPerformed(evt);
            }
        });
        FileMenu.add(changeMode);

        CalculatorMenuBar.add(FileMenu);

        HelpMenu.setText("Help");
        CalculatorMenuBar.add(HelpMenu);

        setJMenuBar(CalculatorMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ButtonEquals, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ButtonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                                .addComponent(Button0, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButtonDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(ButtonSubtraction, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ButtonSquare, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(InputOutputTextField)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(Button1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                        .addComponent(Button4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Button7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Button8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Button5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Button2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Button9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Button6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Button3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(ButtonAddition, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ButtonMultiply, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ButtonDivide, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(ButtonMemoryRecall, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ButtonMemoryClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(ButtonMemoryStore, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, Short.MAX_VALUE))))))
                        .addContainerGap(11, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(InputOutputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button9, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonMemoryStore, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonMemoryClear, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonAddition, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonMemoryRecall, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonSquare, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonSubtraction, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button0, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonEquals, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonMemoryRecallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonMemoryRecallActionPerformed
        InputOutputTextField.setText(memoryStore);
    }//GEN-LAST:event_ButtonMemoryRecallActionPerformed

    private void ButtonEqualsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEqualsActionPerformed
                
        switch ( math_operator ) {
            case '+':
                total2 = total1 + Double.parseDouble( InputOutputTextField.getText( ) ) ;
                break;
            case '-':
                total2 = total1 - Double.parseDouble( InputOutputTextField.getText( ) ) ;
                break;
            case '/':
                total2 = total1 / Double.parseDouble( InputOutputTextField.getText( ) ) ;
                break;
            case '*':
                total2 = total1 * Double.parseDouble( InputOutputTextField.getText( ) ) ;
                break;
        }
        
        InputOutputTextField.setText( Double.toString(total2) );
        total1 = 0;
    }//GEN-LAST:event_ButtonEqualsActionPerformed

    private void Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button1ActionPerformed
        if (InputOutputTextField.getText().equals(zero)){
            InputOutputTextField.setText("");
        }
        String btnOneText = InputOutputTextField.getText() + Button1.getText( );
        InputOutputTextField.setText(btnOneText); 
    }//GEN-LAST:event_Button1ActionPerformed

    private void Button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button4ActionPerformed
        if (InputOutputTextField.getText().equals(zero)){
            InputOutputTextField.setText("");
        }
        String btnOneText = InputOutputTextField.getText() + Button4.getText( );
        InputOutputTextField.setText(btnOneText); 
    }//GEN-LAST:event_Button4ActionPerformed

    private void Button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button7ActionPerformed
        if (InputOutputTextField.getText().equals(zero)){
            InputOutputTextField.setText("");
        }
        String btnOneText = InputOutputTextField.getText() + Button7.getText( );
        InputOutputTextField.setText(btnOneText); 
    }//GEN-LAST:event_Button7ActionPerformed

    private void Button8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button8ActionPerformed
        if (InputOutputTextField.getText().equals(zero)){
            InputOutputTextField.setText("");
        }
        String btnOneText = InputOutputTextField.getText() + Button8.getText( );
        InputOutputTextField.setText(btnOneText); 
    }//GEN-LAST:event_Button8ActionPerformed

    private void Button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button5ActionPerformed
        if (InputOutputTextField.getText().equals(zero)){
            InputOutputTextField.setText("");
        }
        String btnOneText = InputOutputTextField.getText() + Button5.getText( );
        InputOutputTextField.setText(btnOneText); 
    }//GEN-LAST:event_Button5ActionPerformed

    private void Button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button2ActionPerformed
        if (InputOutputTextField.getText().equals(zero)){
            InputOutputTextField.setText("");
        }
        String btnOneText = InputOutputTextField.getText() + Button2.getText( );
        InputOutputTextField.setText(btnOneText); 
    }//GEN-LAST:event_Button2ActionPerformed

    private void Button0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button0ActionPerformed
        if (InputOutputTextField.getText().equals(zero)){
            InputOutputTextField.setText("");
        }
        String btnOneText = InputOutputTextField.getText() + Button0.getText( );
        InputOutputTextField.setText(btnOneText); 
    }//GEN-LAST:event_Button0ActionPerformed

    private void ButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonClearActionPerformed
        total2 = 0;
        InputOutputTextField.setText("0");
    }//GEN-LAST:event_ButtonClearActionPerformed

    private void Button9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button9ActionPerformed
        if (InputOutputTextField.getText().equals(zero)){
            InputOutputTextField.setText("");
        }
        String btnOneText = InputOutputTextField.getText() + Button9.getText( );
        InputOutputTextField.setText(btnOneText); 
    }//GEN-LAST:event_Button9ActionPerformed

    private void Button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button6ActionPerformed
        if (InputOutputTextField.getText().equals(zero)){
            InputOutputTextField.setText("");
        }
        String btnOneText = InputOutputTextField.getText() + Button6.getText( );
        InputOutputTextField.setText(btnOneText); 
    }//GEN-LAST:event_Button6ActionPerformed

    private void Button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button3ActionPerformed
        if (InputOutputTextField.getText().equals(zero)){
            InputOutputTextField.setText("");
        }
        String btnOneText = InputOutputTextField.getText() + Button3.getText( );
        InputOutputTextField.setText(btnOneText); 
    }//GEN-LAST:event_Button3ActionPerformed

    private void ButtonDecimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDecimalActionPerformed
        String btnOneText = InputOutputTextField.getText() + ButtonDecimal.getText( );
        InputOutputTextField.setText(btnOneText);
    }//GEN-LAST:event_ButtonDecimalActionPerformed

    private void ButtonDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDivideActionPerformed
        String button_text = ButtonDivide.getText();
        getOperator(button_text);
    }//GEN-LAST:event_ButtonDivideActionPerformed

    private void ButtonMultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonMultiplyActionPerformed
        String button_text = ButtonMultiply.getText();
        getOperator(button_text);
    }//GEN-LAST:event_ButtonMultiplyActionPerformed

    private void ButtonAdditionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAdditionActionPerformed
        String button_text = ButtonAddition.getText();
        getOperator(button_text);
    }//GEN-LAST:event_ButtonAdditionActionPerformed

    private void ButtonSubtractionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSubtractionActionPerformed
        String button_text = ButtonSubtraction.getText();
        getOperator(button_text);
    }//GEN-LAST:event_ButtonSubtractionActionPerformed

    private void ButtonMemoryStoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonMemoryStoreActionPerformed
        memoryStore = InputOutputTextField.getText();
    }//GEN-LAST:event_ButtonMemoryStoreActionPerformed

    private void ButtonMemoryClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonMemoryClearActionPerformed
        memoryStore = "";
    }//GEN-LAST:event_ButtonMemoryClearActionPerformed

    private void InputOutputTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputOutputTextFieldActionPerformed
        
    }//GEN-LAST:event_InputOutputTextFieldActionPerformed

    private void changeModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeModeActionPerformed
       textModeFrame.setVisible(true);
       
    }//GEN-LAST:event_changeModeActionPerformed

    private void menuCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCloseActionPerformed
        textModeFrame.setVisible(false);
    }//GEN-LAST:event_menuCloseActionPerformed

    private void buttonFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFActionPerformed
        String btnAText = textModeInput.getText() + buttonF.getText( );
        textModeInput.setText(btnAText); 
    }//GEN-LAST:event_buttonFActionPerformed

    private void buttonAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAActionPerformed
        String btnAText = textModeInput.getText() + buttonA.getText( );
        textModeInput.setText(btnAText); 
    }//GEN-LAST:event_buttonAActionPerformed

    private void buttonBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBActionPerformed
        String btnAText = textModeInput.getText() + buttonB.getText( );
        textModeInput.setText(btnAText); 
    }//GEN-LAST:event_buttonBActionPerformed

    private void buttonCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCActionPerformed
        String btnAText = textModeInput.getText() + buttonC.getText( );
        textModeInput.setText(btnAText); 
    }//GEN-LAST:event_buttonCActionPerformed

    private void buttonDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDActionPerformed
        String btnAText = textModeInput.getText() + buttonD.getText( );
        textModeInput.setText(btnAText); 
    }//GEN-LAST:event_buttonDActionPerformed

    private void buttonEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEActionPerformed
        String btnAText = textModeInput.getText() + buttonE.getText( );
        textModeInput.setText(btnAText); 
    }//GEN-LAST:event_buttonEActionPerformed

    private void buttonGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGActionPerformed
        String btnAText = textModeInput.getText() + buttonG.getText( );
        textModeInput.setText(btnAText); 
    }//GEN-LAST:event_buttonGActionPerformed

    private void buttonHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHActionPerformed
        String btnAText = textModeInput.getText() + buttonH.getText( );
        textModeInput.setText(btnAText); 
    }//GEN-LAST:event_buttonHActionPerformed

    private void buttonIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonIActionPerformed
        String btnAText = textModeInput.getText() + buttonI.getText( );
        textModeInput.setText(btnAText); 
    }//GEN-LAST:event_buttonIActionPerformed

    private void buttonJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonJActionPerformed
        String btnAText = textModeInput.getText() + buttonJ.getText( );
        textModeInput.setText(btnAText); 
    }//GEN-LAST:event_buttonJActionPerformed

    private void buttonKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKActionPerformed
        String btnAText = textModeInput.getText() + buttonK.getText( );
        textModeInput.setText(btnAText); 
    }//GEN-LAST:event_buttonKActionPerformed

    private void buttonLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLActionPerformed
        String btnAText = textModeInput.getText() + buttonL.getText( );
        textModeInput.setText(btnAText); 
    }//GEN-LAST:event_buttonLActionPerformed

    private void buttonMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMActionPerformed
        String btnAText = textModeInput.getText() + buttonM.getText( );
        textModeInput.setText(btnAText); 
    }//GEN-LAST:event_buttonMActionPerformed

    private void buttonNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNActionPerformed
        String btnAText = textModeInput.getText() + buttonN.getText( );
        textModeInput.setText(btnAText); 
    }//GEN-LAST:event_buttonNActionPerformed

    private void buttonOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOActionPerformed
        String btnAText = textModeInput.getText() + buttonO.getText( );
        textModeInput.setText(btnAText); 
    }//GEN-LAST:event_buttonOActionPerformed

    private void buttonPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPActionPerformed
        String btnAText = textModeInput.getText() + buttonP.getText( );
        textModeInput.setText(btnAText); 
    }//GEN-LAST:event_buttonPActionPerformed

    private void buttonQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonQActionPerformed
        String btnAText = textModeInput.getText() + buttonQ.getText( );
        textModeInput.setText(btnAText); 
    }//GEN-LAST:event_buttonQActionPerformed

    private void buttonRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRActionPerformed
        String btnAText = textModeInput.getText() + buttonR.getText( );
        textModeInput.setText(btnAText); 
    }//GEN-LAST:event_buttonRActionPerformed

    private void buttonSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSActionPerformed
        String btnAText = textModeInput.getText() + buttonS.getText( );
        textModeInput.setText(btnAText); 
    }//GEN-LAST:event_buttonSActionPerformed

    private void buttonTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTActionPerformed
        String btnAText = textModeInput.getText() + buttonT.getText( );
        textModeInput.setText(btnAText); 
    }//GEN-LAST:event_buttonTActionPerformed

    private void buttonUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUActionPerformed
        String btnAText = textModeInput.getText() + buttonU.getText( );
        textModeInput.setText(btnAText); 
    }//GEN-LAST:event_buttonUActionPerformed

    private void buttonVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVActionPerformed
        String btnAText = textModeInput.getText() + buttonV.getText( );
        textModeInput.setText(btnAText); 
    }//GEN-LAST:event_buttonVActionPerformed

    private void buttonWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonWActionPerformed
        String btnAText = textModeInput.getText() + buttonW.getText( );
        textModeInput.setText(btnAText); 
    }//GEN-LAST:event_buttonWActionPerformed

    private void buttonXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonXActionPerformed
        String btnAText = textModeInput.getText() + buttonX.getText( );
        textModeInput.setText(btnAText); 
    }//GEN-LAST:event_buttonXActionPerformed

    private void buttonYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonYActionPerformed
        String btnAText = textModeInput.getText() + buttonY.getText( );
        textModeInput.setText(btnAText); 
    }//GEN-LAST:event_buttonYActionPerformed

    private void buttonZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonZActionPerformed
        String btnAText = textModeInput.getText() + buttonZ.getText( );
        textModeInput.setText(btnAText); 
    }//GEN-LAST:event_buttonZActionPerformed

    private void buttonSpaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSpaceActionPerformed
        String btnAText = textModeInput.getText() + " ";
        textModeInput.setText(btnAText); 
    }//GEN-LAST:event_buttonSpaceActionPerformed

    private void buttonTextClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTextClearActionPerformed
        textModeInput.setText("");
    }//GEN-LAST:event_buttonTextClearActionPerformed

    private void buttonShiftMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonShiftMouseClicked
        if (buttonShift.isSelected() == true){
            buttonA.setText("a");
            buttonB.setText("b");
            buttonC.setText("c");
            buttonD.setText("d");
            buttonE.setText("e");
            buttonF.setText("f");
            buttonG.setText("g");
            buttonH.setText("h");
            buttonI.setText("i");
            buttonJ.setText("j");
            buttonK.setText("k");
            buttonL.setText("l");
            buttonM.setText("m");
            buttonN.setText("n");
            buttonO.setText("o");
            buttonP.setText("p");
            buttonQ.setText("q");
            buttonR.setText("r");
            buttonS.setText("s");
            buttonT.setText("t");
            buttonU.setText("u");
            buttonV.setText("v");
            buttonW.setText("w");
            buttonX.setText("x");
            buttonY.setText("y");
            buttonZ.setText("z");
            
        }
        else if (buttonShift.isSelected() ==false) {
            buttonA.setText("A");
            buttonB.setText("B");
            buttonC.setText("C");
            buttonD.setText("D");
            buttonE.setText("E");
            buttonF.setText("F");
            buttonG.setText("G");
            buttonH.setText("H");
            buttonI.setText("I");
            buttonJ.setText("J");
            buttonK.setText("K");
            buttonL.setText("L");
            buttonM.setText("M");
            buttonN.setText("N");
            buttonO.setText("O");
            buttonP.setText("P");
            buttonQ.setText("Q");
            buttonR.setText("R");
            buttonS.setText("S");
            buttonT.setText("T");
            buttonU.setText("U");
            buttonV.setText("V");
            buttonW.setText("W");
            buttonX.setText("X");
            buttonY.setText("Y");
            buttonZ.setText("Z");
            
        }
    }//GEN-LAST:event_buttonShiftMouseClicked

    private void convertBinaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertBinaryActionPerformed
        String s = textModeInput.getText();
        byte[] bytes = s.getBytes();
        StringBuilder binary = new StringBuilder();
        for (byte b : bytes)
        {
             int value = b;
             for (int i = 0; i < 8; i++)
                {
                    binary.append((value & 128) == 0 ? 0 : 1);
                    value <<= 1;
                }
        binary.append(' ');
        }
        binaryTextArea.setText("'" + s + "' to binary: " + binary);
        binaryWindow.setVisible(true);
    }//GEN-LAST:event_convertBinaryActionPerformed

    private void ButtonSquareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSquareActionPerformed
       double square = Double.parseDouble(InputOutputTextField.getText());
       double squareTotal = square * square;
       InputOutputTextField.setText(Double.toString(squareTotal)); 
    }//GEN-LAST:event_ButtonSquareActionPerformed

    private void binaryExportActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_binaryExportActionPerformed
    {//GEN-HEADEREND:event_binaryExportActionPerformed
        String s = textModeInput.getText();
        byte[] bytes = s.getBytes();
        StringBuilder binary = new StringBuilder();
        for (byte b : bytes)
        {
             int value = b;
             for (int i = 0; i < 8; i++)
                {
                    binary.append((value & 128) == 0 ? 0 : 1);
                    value <<= 1;
                }
        binary.append(' ');
        }
        String exportString = "'" + s + "' to binary: " + binary;
        
                   
        
        try
        {
            String userHomeFolder = System.getProperty("user.home");
            File textFile = new File(userHomeFolder + "\\Desktop", "BinaryTextConversion.txt");
            BufferedWriter bwr = new BufferedWriter(new FileWriter(textFile));
           
            //write contents of StringBuffer to a file
            bwr.write(exportString);
		
            //flush the stream
            bwr.flush();

            //close the stream
            bwr.close();
        }
        catch (IOException ex)
        {
            Logger.getLogger(CalculatorFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
		
		
        
    }//GEN-LAST:event_binaryExportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculatorFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button0;
    private javax.swing.JButton Button1;
    private javax.swing.JButton Button2;
    private javax.swing.JButton Button3;
    private javax.swing.JButton Button4;
    private javax.swing.JButton Button5;
    private javax.swing.JButton Button6;
    private javax.swing.JButton Button7;
    private javax.swing.JButton Button8;
    private javax.swing.JButton Button9;
    private javax.swing.JButton ButtonAddition;
    private javax.swing.JButton ButtonClear;
    private javax.swing.JButton ButtonDecimal;
    private javax.swing.JButton ButtonDivide;
    private javax.swing.JButton ButtonEquals;
    private javax.swing.JButton ButtonMemoryClear;
    private javax.swing.JButton ButtonMemoryRecall;
    private javax.swing.JButton ButtonMemoryStore;
    private javax.swing.JButton ButtonMultiply;
    private javax.swing.JButton ButtonSquare;
    private javax.swing.JButton ButtonSubtraction;
    private javax.swing.JMenuBar CalculatorMenuBar;
    private javax.swing.JMenu FileMenu;
    private javax.swing.JMenu HelpMenu;
    private javax.swing.JTextField InputOutputTextField;
    private javax.swing.JButton binaryExport;
    private java.awt.TextArea binaryTextArea;
    private javax.swing.JDialog binaryWindow;
    private javax.swing.JButton buttonA;
    private javax.swing.JButton buttonB;
    private javax.swing.JButton buttonC;
    private javax.swing.JButton buttonD;
    private javax.swing.JButton buttonE;
    private javax.swing.JButton buttonF;
    private javax.swing.JButton buttonG;
    private javax.swing.JButton buttonH;
    private javax.swing.JButton buttonI;
    private javax.swing.JButton buttonJ;
    private javax.swing.JButton buttonK;
    private javax.swing.JButton buttonL;
    private javax.swing.JButton buttonM;
    private javax.swing.JButton buttonN;
    private javax.swing.JButton buttonO;
    private javax.swing.JButton buttonP;
    private javax.swing.JButton buttonQ;
    private javax.swing.JButton buttonR;
    private javax.swing.JButton buttonS;
    private javax.swing.JToggleButton buttonShift;
    private javax.swing.JButton buttonSpace;
    private javax.swing.JButton buttonT;
    private javax.swing.JButton buttonTextClear;
    private javax.swing.JButton buttonU;
    private javax.swing.JButton buttonV;
    private javax.swing.JButton buttonW;
    private javax.swing.JButton buttonX;
    private javax.swing.JButton buttonY;
    private javax.swing.JButton buttonZ;
    private javax.swing.JMenuItem changeMode;
    private javax.swing.JButton convertBinary;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuClose;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenu menuHelp;
    private javax.swing.JFrame textModeFrame;
    private javax.swing.JTextField textModeInput;
    // End of variables declaration//GEN-END:variables
}
